// Generated by Xata Codegen 0.29.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Url",
    columns: [
      { name: "full_url", type: "string", notNull: true, defaultValue: "" },
      { name: "short_url", type: "string", unique: true },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Url = InferredTypes["Url"];
export type UrlRecord = Url & XataRecord;

export type DatabaseSchema = {
  Url: UrlRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://Team-37-lsqo6i.us-east-1.xata.sh/db/2short",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
